### ISSUE TITLE
Reordering formerly frozen column doesn't work

### ISSUE THREAD

**Issue by 212324963** [vaadin/px-data-grid#306] opened 2018-01-11 21:21 UTC
- View "Basic examples". 
- Enable "Column Reordering Allowed"

**Current:**
1. Action: Freeze "Last" column
   Result: Column is frozen and moves to position one
2. Unfreeze "Last" column
   Result: Column is unfrozen and stays in position one
3. Drag "Last" column from position one to position two
   Result: Column does not change position

**Expected:**
3. Result:"Last" column changes position changes position back to position two

**Comment by ppeyro** [comment] 2018-01-12 00:50
I believe this might be a duplicate of #309.  There is more debugging info in #309, so might want to close this one?

**Comment by 212324963** [comment] 2018-01-12 01:59
OK

**Comment by Aileen-H** [comment] 2018-01-16 22:02
1/16/18: We will retest to see if fixed. Duplicate!

**Comment by alump** [comment] 2018-01-16 22:02
Fixed.

**Closed by alump** 2018-01-16 22:02 UTC
