### ISSUE TITLE
Multi select not working in paginated grid

### ISSUE THREAD

**Issue by ppeyro** [vaadin/px-data-grid#383] opened 2018-01-17 19:47 UTC
## Description

Can't get multi-select to work when the grid is paginated.
Sample code below.

## Version
Data-grid : V 1.1.0
Browser: Chrome

## Screenshot
![screen shot 2018-01-17 at 11 21 46 am](https://user-images.githubusercontent.com/10835611/35063080-e3bf7ece-fb7a-11e7-98ca-17f43a0ab75a.png)

Code Example:
```
    <px-data-grid-paginated
          table-data='[
              {
                "Tag Name coz we like really long names ": "Tag_Temperature_With_Data_15",
                "Correlated Tags": "Tag_Temperature_With_Data_15",
                "Units": "celsius",
                "Description": "This is AViD Tag Temperature Type description in celsius",
                "Asset": "Tag_Temperature_With_Data_15 GE_SAN_RAMON_1111111",
                "Domain": "GE_SanRamon1111",
                "Location" : "Noth America",
                "Timezone" :"PST"
              },
              {
                "Tag Name coz we like really long names ": "Tag_Temperature_With_Data_15",
                "Correlated Tags": "Tag_Temperature_With_Data_15",
                "Units": "Some fancy temperature units",
                "Description": "This is a test for grouping data",
                "Asset": "Tag_Temperature_With_Data_15 GE_SAN_RAMON_1111111",
                "Domain": "GE_SanRamon1111",
                "Location" : "Noth America",
                "Timezone" :"PST"
              },
              {
                "Tag Name coz we like really long names ": "Tag_Temperature_With_Data_14",
                "Correlated Tags": "Tag_Temperature_With_Data_14",
                "Units": "celsius",
                "Description": "This is AViD Tag Temperature Type description in celsius",
                "Asset": "Tag_Temperature_With_Data_14 GE_SAN_RAMON_1111111",
                "Domain": "GE_SanRamon1111",
                "Location" : "Noth America",
                "Timezone" :"PST"
              },
              {
                "Tag Name coz we like really long names ": "Tag_Temperature_With_Data_19",
                "Correlated Tags": "Tag_Temperature_With_Data_19",
                "Units": "celsius",
                "Description": "This is AViD Tag Temperature Type description in celsius",
                "Asset": "Tag_Temperature_With_Data_19 GE_SAN_RAMON_1111111",
                "Domain": "GE_SanRamon1111",
                "Location" : "Noth America",
                "Timezone" :"PST"
              },
              {
                "Tag Name coz we like really long names ": "Tag_pressure_With_Data_48",
                "Correlated Tags": "Tag_pressure_With_Data_48",
                "Units": "at",
                "Description": "This is AViD Tag pressure2 Type description in celsius",
                "Asset": "Tag_pressure_With_Data_48 GE_SAN_RAMON_1111111",
                "Domain": "GE_SanRamon1111",
                "Location" : "Noth America",
                "Timezone" :"PST"
              },
              {
                "Tag Name coz we like really long names ": "Tag_Temperature_With_Data_05",
                "Correlated Tags": "Tag_Temperature_With_Data_05",
                "Units": "fahrenheit",
                "Description": "This is AViD Tag Temperature Type description",
                "Asset": "Tag_Temperature_With_Data_05 GEffSAN_RAMON_1111111",
                "Domain": "GE_SanRamon1111",
                "Location" : "Noth America",
                "Timezone" :"PST"
              }
            ]'
          selection-mode="multi"
          default-column-width="250px"
          language="en"
          action-menu
          auto-height
          column-reordering-allowed
          table-actions='[{"name":"Export CSV","id":"CSV"}]'
          on-table-action="tableActionListener"
          page-size="5"
          total-item-count="6"
        >
    </px-data-grid-paginated>

**Comment by alump** [comment] 2018-01-17 19:49
Because those errors in console, I assume this is caused by #381

**Comment by ppeyro** [comment] 2018-01-17 19:52
Or possibly, #360?

**Comment by alump** [comment] 2018-01-18 00:36
O yeah, probably both. Error in console is caused by #381, and actual misbehave by #360. Both now fixed, soon released.

**Closed by alump** 2018-01-18 00:36 UTC
