### ISSUE TITLE
Advanced Filtering: Gray line artifacts found after adding filters

### ISSUE THREAD

**Issue by andrealperry** [vaadin/px-data-grid#671] opened 2018-02-14 22:18 UTC
Gray line artifacts found after adding filters and hovering over the input field.

![screen-shot-2018-02-14-at-2 16 38-pm](https://user-images.githubusercontent.com/30873778/36231175-eac1d406-1191-11e8-8133-e1206d6a2097.png)

**Comment by alump** [comment] 2018-02-14 22:54
I think this is done by your default input theming, we are not adding any special styling to input fields as far as I know.

**Comment by limonte** [comment] 2018-02-22 12:59
I can't reproduce this.

@andrealperry please specify the OS and browser you're using.

**Comment by andrealperry** [comment] 2018-02-23 22:38
Nice to have

**Comment by limonte** [comment] 2018-02-26 08:55
Looks like the duplicate of https://github.com/vaadin/px-data-grid/issues/670

If so, please close this so we can keep the communication in one place.

**Closed** 2018-02-27 19:55 UTC
Labels: Q1 2018, waiting for GE response
