### ISSUE TITLE
Advanced Filtering: Single chip is not showing the bottom stroke in Safari

### ISSUE THREAD

**Issue by andrealperry** [vaadin/px-data-grid#559] opened 2018-02-01 00:52 UTC
Steps to reproduce

1. Open Safari (px-data-grid v1.1.7)
2. Select the Table Filters button
3. Select add filter and type in a string value for any column, do not add another filter (one only), select apply. 
4. The chip is not showing the bottom stroke of the chip. 

Screenshot
![screen shot 2018-01-31 at 4 41 53 pm](https://user-images.githubusercontent.com/30873778/35655490-ed6c27f6-06a6-11e8-97dc-efb19a1a6027.png)

If more than one filter is selected, the bottom stroke shows as intended.
![screen shot 2018-01-31 at 4 42 14 pm](https://user-images.githubusercontent.com/30873778/35655525-0e834910-06a7-11e8-8eea-f93c8b420d7d.png)

**Comment by alump** [comment] 2018-02-01 01:03
Duplicate of #542

**Closed by alump** 2018-02-01 01:03 UTC
